import React from 'react';

const PrivacyPolicy: React.FC = () => {
	return (
		<div className="overflow-scroll">
			<div className="container mx-auto p-4 pb-10">
				<h1 className="text-2xl font-bold mb-4">Privacy Policy</h1>
				<p className="flex flex-col mb-3 font-semibold">Updated at 2023-09-07</p>

				<p className="flex flex-col mb-3">
					Meetlily Advertising (&ldquo;we,&ldquo; &ldquo;our,&ldquo; or &ldquo;us&ldquo;) is
					committed to protecting your privacy. This Privacy Policy explains how your personal
					information is collected, used, and disclosed by Meetlily Advertising.
				</p>
				<p className="flex flex-col mb-3">
					This Privacy Policy applies to our website, and its associated subdomains (collectively,
					our &ldquo;Service&ldquo;) alongside our application, Meetlily Advertising. By accessing
					or using our Service, you signify that you have read, understood, and agree to our
					collection, storage, use, and disclosure of your personal information as described in this
					Privacy Policy and our Terms of Service.
				</p>

				<h1 className="text-2xl font-bold mb-4">Definitions and key terms</h1>
				<p className="flex flex-col mb-3">
					To help explain things as clearly as possible in this Privacy Policy, every time any of
					these terms are referenced, are strictly defined as:
				</p>
				<ul className="mt-3">
					<li className="mt-3">
						Cookie: small amount of data generated by a website and saved by your web browser. It is
						used to identify your browser, provide analytics, remember information about you such as
						your language preference or login information.
					</li>
					<li className="mt-3">
						Company: when this policy mentions &ldquo;Company,&ldquo; &ldquo;we,&ldquo;
						&ldquo;us,&ldquo; or &ldquo;our,&ldquo; it refers to MeetLily Advertising, 304 S. Jones
						Blvd Suite #4899 Las Vegas NV, 89107 that is responsible for your information under this
						Privacy Policy.
					</li>
					<li className="mt-3">
						Country: where Meetlily Advertising or the owners/founders of Meetlily Advertising are
						based, in this case is PH
					</li>
					<li className="mt-3">
						Customer: refers to the company, organization or person that signs up to use the
						Meetlily Advertising Service to manage the relationships with your consumers or service
						users.
					</li>
					<li className="mt-3">
						Device: any internet connected device such as a phone, tablet, computer or any other
						device that can be used to visit Meetlily Advertising and use the services.
					</li>
					<li className="mt-3">
						IP address: Every device connected to the Internet is assigned a number known as an
						Internet protocol (IP) address. These numbers are usually assigned in geographic blocks.
						An IP address can often be used to identify the location from which a device is
						connecting to the Internet.
					</li>
					<li className="mt-3">
						Personnel: refers to those individuals who are employed by Meetlily Advertising or are
						under contract to perform a service on behalf of one of the parties.
					</li>
					<li className="mt-3">
						Personal Data: any information that directly, indirectly, or in connection with other
						information — including a personal identification number — allows for the identification
						or identifiability of a natural person.
					</li>
					<li className="mt-3">
						Service: refers to the service provided by Meetlily Advertising as described in the
						relative terms (if available) and on this platform.
					</li>
					<li className="mt-3">
						Third-party service: refers to advertisers, contest sponsors, promotional and marketing
						partners, and others who provide our content or whose products or services we think may
						interest you.
					</li>
					<li className="mt-3">
						Website: site, which can be accessed via this URL: https://www.meetlily.net
					</li>
					<li className="mt-3">
						You: a person or entity that is registered with Meetlily Advertising to use the
						Services.
					</li>
				</ul>
			</div>
		</div>
	);
};

export default PrivacyPolicy;
