'use client';
import React from 'react';

const TermsAndConditions: React.FC = () => {
	return (
		<div className="overflow-scroll">
			<div className="container mx-auto p-4 pb-10">
				<h1 className="text-2xl font-bold mb-4 mt-4 ">Terms & Conditions</h1>
				<p className="flex flex-col mb-3">Updated at 2023-09-07</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">General Terms</h1>
				<p className="flex flex-col mb-3">
					By accessing and placing an order with Meetlily Advertising, you confirm that you are in
					agreement with and bound by the terms of service contained in the Terms & Conditions
					outlined below. These terms apply to the entire website and any email or other type of
					communication between you and Meetlily Advertising.
				</p>
				<p className="flex flex-col mb-3">
					Under no circumstances shall Meetlily Advertising team be liable for any direct, indirect,
					special, incidental or consequential damages, including, but not limited to, loss of data
					or profit, arising out of the use, or the inability to use, the materials on this site,
					even if Meetlily Advertising team or an authorized representative has been advised of the
					possibility of such damages. If your use of materials from this site results in the need
					for servicing, repair or correction of equipment or data, you assume any costs thereof.
				</p>
				<p className="flex flex-col mb-3">
					Meetlily Advertising will not be responsible for any outcome that may occur during the
					course of usage of our resources. We reserve the rights to change prices and revise the
					resources usage policy in any moment.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">License</h1>
				<p className="flex flex-col mb-3">
					Meetlily Advertising grants you a revocable, non-exclusive, non-transferable, limited
					license to download, install and use the website/app strictly in accordance with the terms
					of this Agreement.
				</p>
				<p className="flex flex-col mb-3">
					These Terms & Conditions are a contract between you and Meetlily Advertising (referred to
					in these Terms & Conditions as &ldquo;Meetlily Advertising&ldquo;, &ldquo;us&ldquo;,
					&ldquo;we&ldquo; or &ldquo;our&ldquo;), the provider of the Meetlily Advertising website
					and the services accessible from the Meetlily Advertising website (which are collectively
					referred to in these Terms & Conditions as the &ldquo;Meetlily Advertising
					Service&ldquo;).
				</p>
				<p className="flex flex-col mb-3">
					You are agreeing to be bound by these Terms & Conditions. If you do not agree to these
					Terms & Conditions, please do not use the Meetlily Advertising Service. In these Terms &
					Conditions, &ldquo;you&ldquo; refers both to you as an individual and to the entity you
					represent. If you violate any of these Terms & Conditions, we reserve the right to cancel
					your account or block access to your account without notice.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Definitions and key terms</h1>
				<p className="flex flex-col mb-3">
					To help explain things as clearly as possible in this Terms & Conditions, every time any
					of these terms are referenced, are strictly defined as:
				</p>
				<ul className="mt-3">
					<li className="mt-3">
						Cookie: small amount of data generated by a website and saved by your web browser. It is
						used to identify your browser, provide analytics, remember information about you such as
						your language preference or login information.
					</li>
					<li className="mt-3">
						Company: when this policy mentions &ldquo;Company,&ldquo; &ldquo;we,&ldquo;
						&ldquo;us,&ldquo; or &ldquo;our,&ldquo; it refers to MeetLily Advertising, 304 S. Jones
						Blvd Suite #4899 Las Vegas NV, 89107 that is responsible for your information under this
						Terms & Conditions.
					</li>
					<li className="mt-3">
						Country: where Meetlily Advertising or the owners/founders of Meetlily Advertising are
						based, in this case is PH
					</li>
					<li className="mt-3">
						Device: any internet connected device such as a phone, tablet, computer or any other
						device that can be used to visit Meetlily Advertising and use the services.
					</li>
					<li className="mt-3">
						Service: refers to the service provided by Meetlily Advertising as described in the
						relative terms (if available) and on this platform.
					</li>
					<li className="mt-3">
						Third-party service: refers to advertisers, contest sponsors, promotional and marketing
						partners, and others who provide our content or whose products or services we think may
						interest you.
					</li>
					<li className="mt-3">
						Website: site, which can be accessed via this URL: https://meetlily.net
					</li>
					<li className="mt-3">
						You: a person or entity that is registered with Meetlily Advertising to use the
						Services.
					</li>
				</ul>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Restrictions</h1>
				<p className="flex flex-col mb-3">You agree not to, and you will not permit others to:</p>
				<ul>
					<li className="mt-3">
						License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or
						otherwise commercially exploit the website/app or make the platform available to any
						third party.
					</li>
					<li className="mt-3">
						Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse
						engineer any part of the website/app.
					</li>
					<li className="mt-3">
						Remove, alter or obscure any proprietary notice (including any notice of copyright or
						trademark) of Meetlily Advertising or its affiliates, partners, suppliers or the
						licensors of the website/app.
					</li>
				</ul>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Return and Refund Policy</h1>
				<p className="flex flex-col mb-3">
					Thanks for shopping at Meetlily Advertising. We appreciate the fact that you like to buy
					the stuff we build. We also want to make sure you have a rewarding experience while
					you&quot;re exploring, evaluating, and purchasing our products.
				</p>
				<p className="flex flex-col mb-3">
					As with any shopping experience, there are terms and conditions that apply to transactions
					at Meetlily Advertising. We&quot;ll be as brief as our attorneys will allow. The main
					thing to remember is that by placing an order or making a purchase at Meetlily
					Advertising, you agree to the terms along with Policy.
				</p>
				<p className="flex flex-col mb-3">
					If, for any reason, You are not completely satisfied with any good or service that we
					provide, don&apos;t hesitate to contact us and we will discuss any of the issues you are
					going through with our product.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Your Suggestions</h1>
				<p className="flex flex-col mb-3">
					Any feedback, comments, ideas, improvements or suggestions (collectively,
					&ldquo;Suggestions&ldquo;) provided by you to Meetlily Advertising with respect to the
					website/app shall remain the sole and exclusive property of Meetlily Advertising.
				</p>
				<p className="flex flex-col mb-3">
					Meetlily Advertising shall be free to use, copy, modify, publish, or redistribute the
					Suggestions for any purpose and in any way without any credit or any compensation to you.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Your Consent</h1>
				<p className="flex flex-col mb-3">
					We&apos;ve updated our Terms & Conditions to provide you with complete transparency into
					what is being set when you visit our site and how it&apos;s being used. By using our
					website/app, registering an account, or making a purchase, you hereby consent to our Terms
					& Conditions and agree to its terms.
				</p>
				<p className="flex flex-col mb-3">
					Links to Other Websites Our website contains links to other websites that are not owned or
					controlled by us. Please be aware that we are not responsible for the privacy practices of
					such other websites or third-parties.
				</p>
				<p className="flex flex-col mb-3">
					We encourage you to be aware when you leave our website and to read the terms and
					conditions and privacy policy of each website that you visit.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Changes to Our Terms & Conditions</h1>
				<p className="flex flex-col mb-3">
					You acknowledge and agree that it is your responsibility to review this website and this
					Policy periodically and to be aware of any modifications. We will notify you of any
					changes to this privacy policy by posting those changes on this page.
				</p>

				<h1 className="text-2xl font-bold mb-4 mt-4 ">Contact Us</h1>
				<p className="flex flex-col mb-3">
					If you have any questions or suggestions about our Terms & Conditions, do not hesitate to
					contact us.
				</p>
			</div>
		</div>
	);
};

export default TermsAndConditions;
