import { editor } from 'monaco-editor';

const EditorConfig: editor.IStandaloneEditorConstructionOptions = {
	formatOnPaste: true,
	formatOnType: true,
	minimap: {
		enabled: false
	},
	acceptSuggestionOnCommitCharacter: true,
	acceptSuggestionOnEnter: 'on',
	accessibilitySupport: 'auto',
	autoIndent: 'none',

	automaticLayout: true,
	codeLens: true,
	colorDecorators: true,
	contextmenu: true,
	cursorBlinking: 'blink',
	cursorSmoothCaretAnimation: 'on',
	cursorStyle: 'line',
	disableLayerHinting: false,
	disableMonospaceOptimizations: false,
	dragAndDrop: false,
	fixedOverflowWidgets: false,
	folding: true,
	foldingStrategy: 'auto',
	fontLigatures: false,
	hideCursorInOverviewRuler: false,
	//highlightActiveIndentGuide: true,
	links: true,
	mouseWheelZoom: false,
	multiCursorMergeOverlapping: true,
	multiCursorModifier: 'alt',
	overviewRulerBorder: true,
	overviewRulerLanes: 2,
	quickSuggestions: true,
	quickSuggestionsDelay: 100,
	readOnly: false,
	renderControlCharacters: false,
	renderLineHighlight: 'all',
	renderWhitespace: 'none',
	revealHorizontalRightPadding: 30,
	roundedSelection: true,
	rulers: [],
	scrollBeyondLastColumn: 5,
	scrollBeyondLastLine: true,
	selectOnLineNumbers: true,
	selectionClipboard: true,
	selectionHighlight: true,
	showFoldingControls: 'mouseover',
	smoothScrolling: false,
	suggestOnTriggerCharacters: true,
	wordBasedSuggestions: true,
	wordSeparators: '~!@#$%^&*()-=+[{]}|;:\'",.<>/?',
	wordWrap: 'on',
	wordWrapBreakAfterCharacters: '\t})]?|&,;',
	wordWrapBreakBeforeCharacters: '{([+',
	wordWrapColumn: 80,
	wrappingIndent: 'none'
};

export default EditorConfig;
