'use client'
import { IconType } from "react-icons";
import {RiVideoChatFill, RiSecurePaymentFill, RiRefund2Fill} from 'react-icons/ri'
import { TbApi,TbMovie, TbServer2, TbLayoutGridAdd, TbTools, TbCurrencyRiyal, TbCurrencyDirham, TbCurrencyDinar, TbCurrencyCent, TbCurrencyAfghani, TbCurrencyBahraini, TbCurrencyDogecoin, TbCurrencyWon, TbCurrencyTenge, TbCurrencyZloty, TbCurrencyDram, TbCurrencyEthereum, TbCurrencyLitecoin, TbCurrencyLari } from 'react-icons/tb'
import {HiHomeModern,} from 'react-icons/hi2'
import {LuCalendarClock, LuLayoutGrid, LuRefreshCw, LuCog } from 'react-icons/lu'
import { BsDatabaseAdd,BsPersonAdd, BsBuildingAdd, BsFillHouseAddFill, BsDatabaseUp, BsChevronRight, BsFileRichtextFill, BsFillCalendar2WeekFill, BsFillCalendar2PlusFill, BsFillCalendarXFill, BsFillCalendar2CheckFill, BsCalendarRange, BsCash, BsCashCoin, BsCurrencyEuro } from 'react-icons/bs'
import { BiAddToQueue, BiSolidBookContent, BiRestaurant, BiSolidBusiness } from 'react-icons/bi'
import { MdSwitchAccessShortcutAdd, MdOutlineAdminPanelSettings, MdWorkspacePremium, MdOutlineAddBusiness, MdCardMembership, MdApi, MdOutlineMeetingRoom, MdCurrencyPound, MdOutlineCurrencyLira, MdOutlineCurrencyFranc, MdOutlineCurrencyBitcoin, MdCurrencyRuble, MdCurrencyRupee, MdSupport, MdOutlineLocalShipping } from 'react-icons/md'
import { GiLovers, GiVideoConference, GiCash } from "react-icons/gi";

import { 
    FaArrowUpFromBracket,
    FaRightToBracket,
    FaRightFromBracket,
    FaBlogger,
    FaBots,
    FaReadme,
    FaCarRear,
    FaCartPlus,
    FaChalkboardUser,
    FaDiagramProject,
    FaDollarSign,
    FaDolly,
    FaDownload,
    FaHardDrive,
    FaHandshake,
    FaHotel,
    FaCalendar,
    FaServer,
    FaRProject,
    FaBan,
    FaGraduationCap,
    FaLaptopFile,
    FaXmark,
    FaDatabase,
    FaWindows,
    FaBuilding,
    FaCalendarDays,
    FaClipboardList,
    FaClipboardUser,
    FaGear,
    FaGears,
    FaIdCard,
    FaImages,
    FaHouse,
    FaLaptopCode,
    FaMapLocationDot,
    FaLocationDot,
    FaLocationCrosshairs,
    FaLocationArrow,
    FaPalette,
    FaPaintbrush,
    FaPenToSquare,
    FaPhotoFilm,
    FaPlane,
    FaRobot,
    FaScrewdriverWrench,
    FaShop,
    FaSuitcase,
    FaTaxi,
    FaTicket,
    FaTrashCan,
    FaTruckFast,
    FaTruckRampBox,
    FaRegCreditCard,
    FaRegHeart,
    FaWandMagicSparkles,
    FaPeopleGroup,
    FaPeopleRoof,
    FaMusic,
    FaMasksTheater,
    FaMartiniGlass,
    FaHeadset,
    FaGlasses,
    FaGlobe,
    FaFingerprint,
    FaFlag,
    FaEnvelope,
    FaDesktop,
    FaCloudSunRain,
    FaChartLine,
    FaChartPie,
    FaChartColumn,
    FaCashRegister,
    FaBusinessTime,
    FaBook,
    FaClock,
    FaClockRotateLeft,
    FaTimeline,
    FaInfo,
    FaMoneyCheckDollar,
    FaBuildingColumns,
    FaVideo,
    FaIcons,
    FaFonticons,
    FaRegBell,
    FaWarehouse,
    FaFileInvoice,
    FaUpload,
    FaCloudArrowUp,
    FaListCheck,
    FaUsersGear,
    FaUserTie,
    FaUserAstronaut,
    FaUserClock,
    FaMoneyBillWave,
    FaAddressCard,
    FaAdversal,
    FaMoneyBillTrendUp,
    FaBoxArchive,
    FaDiceD6,
    FaEnvelopesBulk,
    FaHandHoldingDollar,
    FaHouseTsunami,
    FaMedal,
    FaSignature,
    FaSuitcaseRolling,
    FaUserSecret,
    FaRegObjectGroup,
    FaPlaneArrival,
    FaFileContract,
    FaFilePen,
    FaBars,
    FaBarsStaggered,
    FaMagnifyingGlass,
    FaUser,
    FaWpforms,
    FaPersonChalkboard,
    FaCodeBranch,
    FaCode,
    FaPowerOff,
    FaChartSimple,
    FaChartArea,
    FaChartBar,
    FaQuestion,
    FaRegAddressCard,
    FaLock,
    FaCloud,
    FaShieldHalved,
    FaFacebook,
    FaTwitter,
    FaInstagram,
    FaGithub,
    FaGoogle,
    FaGooglePlay,
    FaGooglePlus,
    FaGoogleDrive,
    FaStore,
    FaTrademark,
    FaRegistered,
    FaPesoSign,
    FaYenSign,
    FaCartFlatbed
} from "react-icons/fa6";



const AppIcons: { [key: string]: IconType } = {
    proposals: BsFileRichtextFill,
    payments: RiSecurePaymentFill,
    restaurant:BiRestaurant,
    premium: MdWorkspacePremium,
    chevNext: BsChevronRight,
    googleDrive: FaGoogleDrive,
    googlePlus: FaGooglePlus,
    googlePlay: FaGooglePlay,
    google: FaGoogle,
    github: FaGithub,
    instagram: FaInstagram,
    twitter: FaTwitter,
    facebook: FaFacebook,
    dbBackup: BsDatabaseUp,
    cog: LuCog,
    shield: FaShieldHalved,
    refresh: LuRefreshCw,
    cloud: FaCloud,
    lock: FaLock,
    register: FaRegAddressCard,
    admin: MdOutlineAdminPanelSettings,
    chartCol: FaChartColumn,
    chartPie: FaChartPie,
    chartLine: FaChartLine,
    chartBar: FaChartBar,
    chartArea: FaChartArea,
    chartSimple: FaChartSimple,
    signUp: FaArrowUpFromBracket,
    signOut: FaPowerOff,
    signIn: FaRightToBracket,
    toolsUtils: TbTools,
    addCompany: BsBuildingAdd,
    addHome: BsFillHouseAddFill,
    addUser: BsPersonAdd,
    addIcon: MdSwitchAccessShortcutAdd,
    addBlock: BiAddToQueue,
    addDatabase: BsDatabaseAdd,
    addApp: TbLayoutGridAdd,
    analytics: FaChartLine,
    jobs: FaPersonChalkboard,
    forms: FaWpforms,
    user: FaUser,
    search: FaMagnifyingGlass,
    menuStaggered: FaBarsStaggered,
    menu: FaBars,
    generate: FaFilePen,
    contracts: FaFileContract,
    templates: FaRegObjectGroup,
    vault: FaUserSecret,
    travel: FaPlaneArrival,
    booking: FaSuitcaseRolling,
    sign: FaSignature,
    awards: FaMedal,
    vacation: FaHouseTsunami,
    accounting: FaHandHoldingDollar,
    blocks: FaDiceD6,
    homeRentals: HiHomeModern,
    archive: FaBoxArchive,
    advertising: FaAdversal,
    contacts: FaAddressCard,
    emailCampaign: FaEnvelopesBulk,
    entertainment: FaMasksTheater,
    subscriptions: MdCardMembership,
    apiIcon: MdApi,
    robot: FaUserAstronaut,
    users: FaUsersGear,
    todo: FaListCheck,
    cloudUpload: FaCloudArrowUp,
    upload: FaUpload,
    invoicing: FaFileInvoice,
    warehouse: FaWarehouse,
    api: TbApi,
    notification: FaRegBell,
    icons: FaIcons,
    fonts: FaFonticons,
    video: FaInfo,
    about: FaInfo,
    info: BiSolidBusiness,
    connect: RiVideoChatFill,
    bank: FaBuildingColumns,
    timeline: FaTimeline,
    clockInOut: FaUserClock,
    clock: FaClockRotateLeft,
    timesheet: LuCalendarClock,
    documentation: FaBook,
    pos: FaCashRegister,
    help: FaQuestion,
    weather: FaCloudSunRain,
    dashboard: FaDesktop,
    email: FaEnvelope,
    countries: FaFlag,
    biometrics: FaFingerprint,
    website: FaGlobe,
    knowledge: FaGlasses,
    support: FaHeadset,
    club: FaMartiniGlass,
    music: FaMusic,
    employee: FaUserTie,
    hr: FaBusinessTime,
    theme: FaWandMagicSparkles,
    favorite: FaRegHeart,
    creditCard: FaRegCreditCard,
    trash: FaTrashCan,
    server: FaServer,
    events: FaMasksTheater,
    ticketing: MdSupport,
    hotel: FaHotel,
    blogs: FaBlogger,
    aiAssist: FaBots,
    calendar: FaCalendar,
    carRental: FaCarRear,
    taxi: FaTaxi,
    cart: FaCartPlus,
    board: FaChalkboardUser,
    flow: FaDiagramProject,
    sales: FaMoneyBillTrendUp,
    inventory: FaDolly,
    delivery: FaTruckFast,
    moving: FaTruckRampBox,
    fileManagement: FaDownload,
    storage: FaHardDrive,
    crm: FaHandshake,
    project: FaLaptopFile,
    projects: FaLaptopFile,
    ban: FaBan,
    learn: FaGraduationCap,
    dating: GiLovers,
    cms: BiSolidBookContent,
    close: FaXmark,
    database: FaDatabase,
    apps: LuLayoutGrid,
    appointment: BsCalendarRange,
    appointments: BsFillCalendar2WeekFill,
    addAppointment: BsFillCalendar2PlusFill,
    deleteAppointment: BsFillCalendarXFill,
    checkAppointmnet: BsFillCalendar2CheckFill,
    company: BsBuildingAdd,
    notes: FaPenToSquare,
    account: FaClipboardUser,
    configure: FaGear,
    gears: FaGears,
    profile: FaIdCard,
    ecommerce: FaShop,
    shop: FaStore,
    cash: BsCash,
    expenses: BsCashCoin,
    dollar: FaDollarSign,
    peso: FaPesoSign,
    riyal: TbCurrencyRiyal,
    yen: FaYenSign,
    dinar: TbCurrencyDinar,
    cent: TbCurrencyCent,
    afghani: TbCurrencyAfghani,
    bahraini:TbCurrencyBahraini,
    dogecoin: TbCurrencyDogecoin,
    won: TbCurrencyWon,
    tenge: TbCurrencyTenge,
    dram: TbCurrencyDram,
    ethereum: TbCurrencyEthereum,
    litecoin: TbCurrencyLitecoin,
    lari: TbCurrencyLari,
    zloty: TbCurrencyZloty,
    euro: BsCurrencyEuro,
    dirham: TbCurrencyDirham,
    pound: MdCurrencyPound,
    lira: MdOutlineCurrencyLira,
    franc: MdOutlineCurrencyFranc,
    ruble: MdCurrencyRuble,
    rupee: MdCurrencyRupee,
    bitcoin: MdOutlineCurrencyBitcoin,
    trademark: FaTrademark,
    registered: FaRegistered,
    addShop: MdOutlineAddBusiness,
    gallery: FaPhotoFilm,
    home: FaHouse,
    code: FaLaptopCode,
    map: FaMapLocationDot,
    marker: FaLocationDot,
    currentLocation: FaLocationCrosshairs,
    location: FaLocationArrow,
    draw: FaPalette,
    paint: FaPaintbrush,
    airline: FaPlane,
    aiBot: FaRobot,
    repair: FaScrewdriverWrench,
    movies: TbMovie,
    develop: FaCode,
    integration: FaCodeBranch,
    hosting: TbServer2,
    conference: GiVideoConference,
    meetings: MdOutlineMeetingRoom,
    refunds: RiRefund2Fill,
    products: FaCartFlatbed,
    shipping: MdOutlineLocalShipping,
    financial: GiCash,
}

export default AppIcons;