'use client'
import { 
    FaPeopleLine, 
    FaReact,
    FaFacebookF,
    FaFacebookMessenger,
    FaGoogleDrive,
    FaGooglePlay,
    FaGooglePlusG,
    FaGoogle,
    FaGoogleWallet,
    FaGooglePay,
    FaJs,
    FaPython,
    FaGithub,
    FaTwitter,
    FaInstagram,
    FaAws,
    FaMobile,
    FaAndroid,
    FaApple,
    FaLinux,
    FaMicrosoft,
    FaWindows,
    FaAmazonPay,
    FaAmazon,
    FaSlack,
    FaCcMastercard,
    FaCcPaypal,
    FaCcStripe,
    FaCcVisa,
    FaCodepen,
    FaCcApplePay,
    FaBlogger,
    FaBitcoin,
    FaBehance,
    FaAppStore,
    FaAlgolia,
    FaAirbnb,
    FaAngular,
    FaAtlassian,
    FaAutoprefixer,
    FaBluetooth,
    FaBootstrap,
    FaBots,
    FaBtc,
    FaChrome,
    FaConfluence,
    FaCreativeCommons,
    FaCss3,
    FaDev,
    FaDigitalOcean,
    FaDigg,
    FaDiscord,
    FaDiscourse,
    FaDrupal,
    FaDocker,
    FaDribbble,
    FaDropbox,
    FaEbay,
    FaEdge,
    FaEthereum,
    FaEvernote,
    FaFedex,
    FaFigma,
    FaFedora,
    FaFirefox,
    FaFlickr,
    FaFontAwesome,
    FaFoursquare,
    FaGit,
    FaGitlab,
    FaGolang,
    FaHtml5,
    FaInternetExplorer,
    FaJsfiddle,
    FaJira,
    FaKickstarter,
    FaLaravel,
    FaLess,
    FaMagento,
    FaLyft,
    FaMailchimp,
    FaNapster,
    FaNodeJs,
    FaNode,
    FaOpencart,
    FaOpera,
    FaPhp,
    FaPinterest,
    FaRaspberryPi,
    FaReadme,
    FaReddit,
    FaSafari,
    FaSalesforce,
    FaRust,
    FaSass,
    FaShopify,
    FaSkype,
    FaSnapchat,
    FaSoundcloud,
    FaSpotify,
    FaSquarespace,
    FaSquareYoutube,
    FaStackOverflow,
    FaSquareWhatsapp,
    FaTelegram,
    FaTwitch,
    FaTumblr,
    FaUbuntu,
    FaTrello,
    FaTiktok,
    FaUnsplash,
    FaUps,
    FaUsb,
    FaViber,
    FaVuejs,
    FaVimeo,
    FaWaze,
    FaWhatsapp,
    FaWeebly,
    FaWeibo,
    FaWordpress,
    FaWix,
    FaWikipediaW,
    FaXbox,
    FaYahoo,
    FaYarn,
    FaYoast,
    FaYoutube,
    FaAtom,
    FaBanSmoking,
    FaCalendarPlus,
    FaCalendarMinus,
    FaCarRear,
    FaCartPlus,
    FaChalkboardUser,
    FaComputer,
    FaCopyright,
    FaComputerMouse,
    FaCrop,
    FaDiagramProject,
    FaDollarSign,
    FaDolly,
    FaDownload,
    FaEllipsis,
    FaEraser,
    FaFileCsv,
    FaFileInvoice,
    FaFileImage,
    FaFileExport,
    FaFileContract,
    FaFileCode,
    FaFilePdf,
    FaFileWaveform,
    FaFileSignature,
    FaFileWord,
    FaFilePowerpoint,
    FaFileVideo,
    FaHardDrive,
    FaHandshake,
    FaHeadphonesSimple,
    FaHeartPulse,
    FaHotel,
    FaMapLocationDot
} from "react-icons/fa6";
import { IconType } from "react-icons";

const FaIcons: { [key: string]: IconType } = {
    hotel: FaHotel,
    location: FaMapLocationDot,
    pulse: FaHeartPulse,
    headphone: FaHeadphonesSimple,
    people: FaPeopleLine,
    react: FaReact,
    facebook: FaFacebookF,
    messenger: FaFacebookMessenger,
    googleDrive: FaGoogleDrive,
    googlePlay: FaGooglePlay,
    googlePlus: FaGooglePlusG,
    google: FaGoogle,
    googleWallet: FaGoogleWallet,
    googlePay: FaGooglePay,
    js: FaJs,
    python: FaPython,
    github: FaGithub,
    twitter: FaTwitter,
    instagram: FaInstagram,
    aws: FaAws,
    mobile: FaMobile,
    android: FaAndroid,
    apple: FaApple,
    linux: FaLinux,
    microsoft: FaMicrosoft,
    windows: FaWindows,
    amazonPay: FaAmazonPay,
    amazon: FaAmazon,
    slack: FaSlack,
    mastercard: FaCcMastercard,
    paypal: FaCcPaypal,
    stripe: FaCcStripe,
    visa: FaCcVisa,
    codepen: FaCodepen,
    applePay: FaCcApplePay,
    blogger: FaBlogger,
    bitcoin: FaBitcoin,
    behance: FaBehance,
    appStore: FaAppStore,
    algolia: FaAlgolia,
    airbnb: FaAirbnb,
    angular: FaAngular,
    atlassian: FaAtlassian,
    autoprefixer: FaAutoprefixer,
    bluetooth: FaBluetooth,
    bootstrap: FaBootstrap,
    bots: FaBots,
    btc: FaBtc,
    chrome: FaChrome,
    confluence: FaConfluence,
    creativeCommons: FaCreativeCommons,
    css3: FaCss3,
    dev: FaDev,
    digitalOcean: FaDigitalOcean,
    digg: FaDigg,
    discord: FaDiscord,
    discourse: FaDiscourse,
    drupal: FaDrupal,
    docker: FaDocker,
    dribbble: FaDribbble,
    dropbox: FaDropbox,
    ebay: FaEbay,
    edge: FaEdge,
    ethereum: FaEthereum,
    evernote: FaEvernote,
    fedex: FaFedex,
    figma: FaFigma,
    fedora: FaFedora,
    firefox: FaFirefox,
    flickr: FaFlickr,
    fontAwesome: FaFontAwesome,
    foursquare: FaFoursquare,
    git: FaGit,
    gitlab: FaGitlab,
    golang: FaGolang,
    html5: FaHtml5,
    internetExplorer: FaInternetExplorer,
    jsfiddle: FaJsfiddle,
    jira: FaJira,
    kickstarter: FaKickstarter,
    laravel: FaLaravel,
    less: FaLess,
    magento: FaMagento,
    lyft: FaLyft,
    mailchimp: FaMailchimp,
    napster: FaNapster,
    nodeJs: FaNodeJs,
    node: FaNode,
    opencart: FaOpencart,
    opera: FaOpera,
    php: FaPhp,
    pinterest: FaPinterest,
    raspberryPi: FaRaspberryPi,
    readme: FaReadme,
    reddit: FaReddit,
    safari: FaSafari,
    salesforce: FaSalesforce,
    rust: FaRust,
    sass: FaSass,
    shopify: FaShopify,
    skype: FaSkype,
    snapchat: FaSnapchat,
    soundcloud: FaSoundcloud,
    spotify: FaSpotify,
    squarespace: FaSquarespace,
    youtubeSquare: FaSquareYoutube,
    stackOverflow: FaStackOverflow,
    whatsappSquare: FaSquareWhatsapp,
    telegram: FaTelegram,
    twitch: FaTwitch,
    tumblr: FaTumblr,
    ubuntu: FaUbuntu,
    trello: FaTrello,
    tiktok: FaTiktok,
    unsplash: FaUnsplash,
    ups: FaUps,
    usb: FaUsb,
    viber: FaViber,
    vuejs: FaVuejs,
    vimeo: FaVimeo,
    waze: FaWaze,
    whatsapp: FaWhatsapp,
    weebly: FaWeebly,
    weibo: FaWeibo,
    wordpress: FaWordpress,
    wix: FaWix,
    wikipedia: FaWikipediaW,
    xbox: FaXbox,
    yahoo: FaYahoo,
    yarn: FaYarn,
    yoast: FaYoast,
    youtube: FaYoutube,
    atom: FaAtom,
    calendarPlus: FaCalendarPlus,
    calendarMinus: FaCalendarMinus,
    carRear: FaCarRear,
    cartPlus: FaCartPlus,
    chalkboardUser: FaChalkboardUser,
    computer: FaComputer,
    copyright: FaCopyright,
    computerMouse: FaComputerMouse,
    crop: FaCrop,
    diagramProject: FaDiagramProject,
    dollarSign: FaDollarSign,
    dolly: FaDolly,
    download: FaDownload,
    ellipsis: FaEllipsis,
    eraser: FaEraser,
    fileCsv: FaFileCsv,
    fileInvoice: FaFileInvoice,
    fileImage: FaFileImage,
    fileExport: FaFileExport,
    fileContract: FaFileContract,
    fileCode: FaFileCode,
    filePdf: FaFilePdf,
    fileWaveform: FaFileWaveform,
    fileSignature: FaFileSignature,
    fileWord: FaFileWord,
    filePowerpoint: FaFilePowerpoint,
    fileVideo: FaFileVideo,
    hardDrive: FaHardDrive,
    handshake: FaHandshake,
    headphonesSimple: FaHeadphonesSimple,
    heartPulse: FaHeartPulse,
    mapLocationDot: FaMapLocationDot,
}

export default FaIcons;


