'use client';

import { IconType } from "react-icons";
import { FiHeart, FiStar, FiCircle } from "react-icons/fi";
import { 
    SiNextdotjs, 
    SiTypescript, 
    SiPrisma, 
    SiRemix,
    SiMicrosoftazure,
    SiMysql,
    SiPostgresql,
    SiSqlite,
    SiGraphql,
    SiJson,
    SiMongodb,
    SiAmazonalexa, 
    SiSupabase,
    SiFirebase,
    SiTailwindcss
} from "react-icons/si";
import { AiOutlineLoading3Quarters, AiOutlineWindows, AiOutlineConsoleSql } from "react-icons/ai";
import { BsDiagram3Fill, BsFiletypeJson } from "react-icons/bs";
import FaIcons from "./FAIcons";
import { 
    BiDollar 
} from "react-icons/bi";
import { TbPhotoPlus } from "react-icons/tb";
import { IoIosClose } from "react-icons/io";
import { GiLovers } from "react-icons/gi";
//https://react-icons.github.io/react-icons/icons?name=hi2
import { 
    HiSquaresPlus, 
    HiOutlineCalendarDays, 
    HiOutlineCog6Tooth, 
    HiOutlineClock,
    HiOutlineEnvelope,
    HiOutlineHome,
    HiOutlineMagnifyingGlass,
    HiOutlinePaintBrush,
    HiOutlineTrash,
    HiOutlineWrenchScrewdriver,
    HiMiniCalendarDays,
    HiMiniChatBubbleLeftEllipsis,
    HiMiniCheck,
    HiMiniCircleStack,
    HiMiniCodeBracket,
    HiMiniCreditCard,
    HiMiniLink,
    HiMiniRectangleGroup,
    HiMiniServerStack,
    HiMiniShoppingBag,
    HiMiniShoppingCart,
    HiMiniTableCells,
    HiMiniPower,
    HiMiniPhoto,
    HiMiniMicrophone,
    HiMiniMapPin,
    HiMiniMap,
    HiMiniPencilSquare,
    HiMiniLockClosed,
    HiMiniLockOpen,
    HiMiniEllipsisVertical,
    HiMiniEllipsisHorizontal,
    HiMiniComputerDesktop,
    HiMiniChevronRight,
    HiMiniChevronLeft,
    HiOutlineSquares2X2,
    HiOutlineFolderOpen,
    HiVideoCamera,
    HiRectangleGroup,
    HiPlus,
    HiMinus,
    HiHomeModern,
    HiCube,
    HiCommandLine,
    HiChevronDown,
    HiChevronUp,
    HiCamera,
    HiBuildingOffice2,
    HiBuildingStorefront,
    HiBriefcase,
    HiBell,
    HiBars4,
    HiArrowPath,
    HiArchiveBox,
    HiArrowsPointingOut,
    HiArrowsPointingIn,
    HiAtSymbol,
    HiBugAnt,
    HiEye,
    HiKey,
    HiMusicalNote,
    HiNewspaper,
    HiNoSymbol,
    HiPhone,
    HiPaperAirplane,
    HiPrinter,
    HiRadio,
    HiScissors,
    HiSpeakerWave,
    HiSpeakerXMark,
    HiStar,
    HiTrophy,
    HiTruck,
    HiWallet,
    HiOutlineAcademicCap,
    HiAcademicCap,
    HiUserGroup,
    HiOutlineChartPie,
    HiOutlineChartBar,
    HiMiniChartBar,
} from "react-icons/hi2";
import AppIcons from "./AppIcons";


const Icons: { [key: string]: IconType } = {
    heart: FiHeart,
    star: FiStar,
    circle: FiCircle,
    check: HiMiniCheck,
    close: IoIosClose,
    dollar: BiDollar,
    image: TbPhotoPlus,
    loading: AiOutlineLoading3Quarters,
    appointment: HiOutlineCalendarDays,
    settings: HiOutlineCog6Tooth,
    clock: HiOutlineClock,
    email: HiOutlineEnvelope,
    home: HiOutlineHome,
    search: HiOutlineMagnifyingGlass,
    draw: HiOutlinePaintBrush,
    delete: HiOutlineTrash,
    configure: HiOutlineWrenchScrewdriver,
    calendar: HiMiniCalendarDays,
    chat: HiMiniChatBubbleLeftEllipsis,
    database: HiMiniCircleStack,
    code: HiMiniCodeBracket,
    payment: HiMiniCreditCard,
    link: HiMiniLink,
    layout: HiMiniRectangleGroup,
    server: HiMiniServerStack,
    cart: HiMiniShoppingCart,
    shop: HiMiniShoppingBag,
    table: HiMiniTableCells,
    off: HiMiniPower,
    photo: HiMiniPhoto,
    microphone: HiMiniMicrophone,
    map: HiMiniMap,
    marker: HiMiniMapPin,
    edit: HiMiniPencilSquare,
    unlock: HiMiniLockOpen,
    lock: HiMiniLockClosed,
    vMenu: HiMiniEllipsisVertical,
    hMenu: HiMiniEllipsisHorizontal,
    dashboard: HiMiniComputerDesktop,
    back: HiMiniChevronLeft,
    next: HiMiniChevronRight,
    cms: HiRectangleGroup,
    upload: HiOutlineFolderOpen,
    video: HiVideoCamera,
    plus: HiPlus,
    minus: HiMinus,
    hModern: HiHomeModern,
    cube: HiCube,
    terminal: HiCommandLine,
    down: HiChevronDown,
    up: HiChevronUp,
    camera: HiCamera,
    building: HiBuildingOffice2,
    store: HiBuildingStorefront,
    business: HiBriefcase,
    alert: HiBell,
    navigation: HiBars4,
    refresh: HiArrowPath,
    archive: HiArchiveBox,
    minimize: HiArrowsPointingIn,
    maximize: HiArrowsPointingOut,
    at: HiAtSymbol,
    bug: HiBugAnt,
    view: HiEye,
    key: HiKey,
    music: HiMusicalNote,
    news: HiNewspaper,
    ban: HiNoSymbol,
    phone: HiPhone,
    send: HiPaperAirplane,
    print: HiPrinter,
    radio: HiRadio,
    cut: HiScissors,
    volume: HiSpeakerWave,
    mute: HiSpeakerXMark,
    delivery: HiTruck,
    vip: HiTrophy,
    wallet: HiWallet,
    lms: HiAcademicCap,
    dating: GiLovers,
    bar: HiOutlineChartBar,
    pie: HiOutlineChartPie,
    analytics: HiMiniChartBar,
    nextJS: SiNextdotjs
};

export default Icons;

